# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=45)),
                ('product_description', models.CharField(max_length=45)),
                ('product_history', models.TextField()),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('product_reviews', models.TextField(max_length=248)),
            ],
        ),
    ]
