# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
    ]
